#!/bin/bash

verilator --trace \
   --cc rtl/x_23K640.sv \
   --cc rtl/x_23K640_sck.sv \
   --cc rtl/x_23K640_data.sv \
   --cc verif/app_driver.cpp \
   --cc verif/logger.cpp \
   --exe verif/x_23K640_tb.cpp \
   -Iverif/include/

make -C obj_dir -f Vx_23K640.mk Vx_23K640

